### ISSUE TITLE
fix: refine settings screen

### ISSUE THREAD

**Issue by exKAZUu** [WillBooster/plantuml-visualizer#681] opened 2022-02-20 04:15 UTC
<img width="579" alt="image" src="https://user-images.githubusercontent.com/436237/154828178-ab20ba24-75b4-44c0-85e2-9f7189b8b7b7.png">

**Comment by kumachan-mis** [comment] 2022-02-22 02:08
duplicate of #596

**Closed by kumachan-mis** 2022-02-22 02:08 UTC
